### ISSUE TITLE
STM32 details in imxrtral.py

### ISSUE THREAD

**Issue by mciantyre** [imxrt-rs/imxrt-ral#2]
We're maintaining STM32 details in the `imxrtral.py` script. This issue lists the details that I found during some recent RAL prototyping.

- [ ] Most `UNSAFE_REGISTERS` refer to STM32 registers. We should remove these names, and identify equivalent unsafe i.MX RT registers.

    https://github.com/imxrt-rs/imxrt-ral/blob/aae64342e2cb7491707776fd9cc70b100f8d00c9/imxrtral.py#L114-L132

- [ ] The `common_names` function has a set of special cases for STM32 names. We could remove this branch, documentation, and tests; then add our own special cases.

    https://github.com/imxrt-rs/imxrt-ral/blob/aae64342e2cb7491707776fd9cc70b100f8d00c9/imxrtral.py#L1793-L1805

- [ ] `refactor_peripheral_instances` has a special case for combining STM32 timers. Could be removed.

    https://github.com/imxrt-rs/imxrt-ral/blob/aae64342e2cb7491707776fd9cc70b100f8d00c9/imxrtral.py#L1345-L1350

- [x] There are a few hits for "stm32" throughout the code. One instance leaks into [our RAL documentation](https://docs.rs/imxrt-ral/0.4.0/imxrt_ral/imxrt105/imxrt1052/index.html), generating docs that read "stm32ral module for imxrt1052."

**Comment by teburd** [comment]
With the upcoming usage of chiptool this seems invalid
