### ISSUE TITLE
FlexIO missing registers for shifters and timers

### ISSUE THREAD

**Issue by shumpohl** [imxrt-rs/imxrt-ral#31]
Accoring to the reference all FlexIO periphials have 8 shifters and timers fo the 1060 e.g. the teensy 4.

[This](https://forum.pjrc.com/threads/66201-Teensy-4-1-How-to-start-using-FlexIO) forum post says that this information is wrong in some other resources.

**Comment by mciantyre** [comment]
Acknowledged. The 1060 reference manual (revision 3) states there are eight shifter and timer registers. However, today's `imxrt-ral` only exposes four of those eight registers.

https://github.com/imxrt-rs/imxrt-ral/blob/0b0d9689aabf19eabfb89abc8465cc4ec8f07cb8/src/blocks/imxrt1061/flexio.rs#L32-L66

I haven't checked, but my guess is that this is an issue in the SVD files. We should be able to patch that.

We should also check the FlexIO peripherals for other chips, making sure they have the expected number of shifters and timers.

**Comment by mciantyre** [comment]
> We should also check the FlexIO peripherals for other chips, making sure they have the expected number of shifters and timers.

Checked as part of #41 by inspecting reference manuals. The 1060 and the 1170 has eight shifters and timers, but only the 1060's SVDs suggest that there's only four of each.
