### ISSUE TITLE
Missing register field - FlexSPI - `MCR0` - `SERCLKDIV`

### ISSUE THREAD

**Issue by Finomnis** [imxrt-rs/imxrt-ral#36]
Various MCUs are missing the `SERCLKDIV` field in the FlexSPI `MCR0` register. These fields are missing in the SVD, so they're also missing in this crate. To fix this, use SVD patches to re-introduce the field.

This affects the following families and MCUs.

- 1020
  - 1021
- 1050
  - 1051
  - 1052
- 1060
  - 1061
  - 1062
  - 1064

The 1011 and 1176 SVDs are not affected. This field is marked as "reserved" in an older 1015 reference manual. Download the latest RM and double check this once NXP's website exits maintenance mode...

**Comment by mciantyre** [comment]
For folks who want to patch this, here's an example of how to use `svdtools` to add a new register field with an enum of values.

https://github.com/imxrt-rs/imxrt-ral/blob/0b0d9689aabf19eabfb89abc8465cc4ec8f07cb8/devices/common_patches/lpuart_ridmae.yaml#L1-L12

**Comment by mciantyre** [comment]
Available in 0.5.2.
