### ISSUE TITLE
FlexIO module naming consistency for 1011, 1021

### ISSUE THREAD

**Issue by mciantyre** [imxrt-rs/imxrt-ral#37]
Since the 1011 and 1021 MCUs only have one FlexIO peripheral instance, the RAL generation pipeline names the module as `flexio1`.

https://github.com/imxrt-rs/imxrt-ral/blob/0b0d9689aabf19eabfb89abc8465cc4ec8f07cb8/src/imxrt1011.rs#L704

This prevents us from using a consistent module path in Rust code. See the (current) build status of imxrt-rs/imxrt-hal#139 for an example of an issue that manifests when names aren't consistent.

Use renaming techniques (SVD patches, `raltool` transforms) to rename `flexio1` to `flexio` in 1011 and 1021 MCUs.

**Comment by mciantyre** [comment]
Here's how this was solved for ADC and PWM peripherals on the 1011. Something similar should still work for FlexIO.

https://github.com/imxrt-rs/imxrt-ral/blob/0b0d9689aabf19eabfb89abc8465cc4ec8f07cb8/devices/imxrt1011.yaml#L17-L30

**Comment by Finomnis** [comment]
This is a breaking change, though, so it will require a major version bump. Although you are probably aware.

**Comment by mciantyre** [comment]
I haven't tried anything yet, but I think there's a backwards-compatible approach. After correcting the module name, I'll create a 0.5 release branch. Then, I'll manually add modules for the old name, something like

```rust
#[deprecated(since = "0.5.1", note = "Use the 'flexio' module instead of this module")]
pub mod flexio1 {
  pub use super::flexio::*;
}
```

If that all works, we could release that in 0.5.1 for immediate use in the HAL. I assume the maintainer burden to keep the patches for the rest of the 0.5 release. A commit with some smoke tests could help us make sure this all works, and help me with any longer-term maintenance.

---

The path `imxrt_ral::flexio::FLEXIO`, without the '1' on FLEXIO, is consistent with the way [the ADC instance types and pointer items are generated](https://github.com/imxrt-rs/imxrt-ral/blob/0b0d9689aabf19eabfb89abc8465cc4ec8f07cb8/src/imxrt1011.rs#L361-L368) after the 1011 module rename. The ADC instance types / pointer item is just `ADC`, not `ADC1`. (Good eye; this would play into the aliasing idea.)

Specific to the clock gate routines, the HAL handles this with a branch that checks for the "sole instance" const generic. [Here's the ADC clock gate implementation](https://github.com/imxrt-rs/imxrt-hal/blob/4b91aed8395e39c1f7b5e224491ea6fc70749b21/src/chip/imxrt10xx/ccm/clock_gate.rs#L350-L359).

**Comment by Finomnis** [comment]
@mciantyre I added [the first part](https://github.com/imxrt-rs/imxrt-ral/pull/38) of your suggestion. If you volunteer to provide the `0.5.1`, then I feel like this is all set :)

**Comment by Finomnis** [comment]
I also added a namespace existence smoke test in that PR.

**Comment by Finomnis** [comment]
@mciantyre Any feedback on this? What's missing?
