### ISSUE TITLE
Incorrectly named register entries in `106x`

### ISSUE THREAD

**Issue by Finomnis** [imxrt-rs/imxrt-ral#39]
Relevant file: `src/blocks/imxrt1061/ccm.rs`

Register `CS1CDR`, according to [the documentation](https://www.pjrc.com/teensy/IMXRT1060RM_rev3.pdf), has the following fields:
- `27–25`: `FLEXIO2_CLK_PODF`
- `11–9`: `FLEXIO2_CLK_PRED`

Our generated code, however, has the following fields in `CS1CDR`:
- `27-25`: `FLEXIO1_CLK_PODF`
- `11-9`: `FLEXIO1_CLK_PRED`

The actual registers that *should* be named `FLEXIO1_CLK_PODF` and `FLEXIO1_CLK_PRED` are also named so, meaning these names exists twice.

I guess this is an error in the svd.

**Comment by mciantyre** [comment]
This looks similar to #32. Does #33 address this?

**Comment by Finomnis** [comment]
I think so :)
