### ISSUE TITLE
Missing NVIC Registers

### ISSUE THREAD

**Issue by jman168** [imxrt-rs/imxrt-ral#49]
When working with the RT1176_M7 I discovered that the NVIC peripheral is missing registers. For example, I need to enable the PIT2 interrupt (IRQ number 156), so I go to set bit 28 of NVICISER4, but oh no, there's no NVICISER4, it stops at NVICISER3! There are four 32 bit wide NVIC IRQ enable registers which works out to 128 IRQs, but looking at the reference manual there's over 200. Looking at the SVD file, they're missing there as well for some reason. I haven't looked at any other processors, but I know that for the M4 and M7 of the RT1176 this is an issue. It's also missing the IRQ priority and associated registers, it's as if the SVD just cuts off almost half of the IRQs.

**Comment by jman168** [comment]
Found something interesting, if you look at the SVD from the most recent NXP SDK (2.16.0), it _does_ have the missing registers. Might be as simple as just updating the SVD in this repo? I'm not sure what the process for that looks like or how many things that would break in the process.

**Comment by mciantyre** [comment]
Would [the `cortex-m` crate](https://docs.rs/cortex-m/0.7.7/cortex_m/) work for you? [Their NVIC API](https://docs.rs/cortex-m/0.7.7/cortex_m/peripheral/struct.NVIC.html) is convenient, and `imxrt-ral` should play well with it. Enabling the PIT2 interrupt would look like

```rust
unsafe { cortex_m::peripheral::NVIC::unmask(imxrt_ral::Interrupt::PIT2) };
```

If you're a real do-it-yourself-er, [here's the raw registers](https://docs.rs/cortex-m/0.7.7/cortex_m/peripheral/nvic/struct.RegisterBlock.html).

---

We intentionally removed NVIC from the 1000 series in #17. I'm inclined to remove the NVIC from the 1176 for consistency.

**Comment by mciantyre** [comment]
#50 removes all NVIC registers from the 1176.
