### ISSUE TITLE
Removing Cortex-M peripheral API

### ISSUE THREAD

**Issue by mciantyre** [imxrt-rs/imxrt-ral#7]
The imxrt-ral crate provides not just an API for i.MX RT peripherals, but also [an API for cortex-m peripherals](https://docs.rs/imxrt-ral/0.4.1/imxrt_ral/cortex_m/index.html). While it might be nice to have a consistent API for CM peripherals, it duplicates what's already available from [the `cortex-m` crate](https://docs.rs/cortex-m/0.7.1/cortex_m/index.html).

Given that the `cortex-m` crate already provides these peripherals, would anyone be opposed to removing the `cortex_m` module from `imxrt_ral`?

**Comment by teburd** [comment]
I think its a fine idea

**Comment by mciantyre** [comment]
Merged in #15.
